# -------------------------------------------------------------------------------
# cinc-runner Image Build
#
# Project: Munchbox / Author: Alex Freidah
# -------------------------------------------------------------------------------

IMAGE := cinc-runner

include ../_common.mk
