# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for cni.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
