# .pre-commit-config.yaml
repos:
  # Go formatting, linting, and module management
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        files: ^cdktf/.*\.go$

      - id: go-vet
        name: go vet
        entry: bash -c 'cd cdktf && go vet ./...'
        language: system
        pass_filenames: false
        files: ^cdktf/.*\.go$

      - id: go-mod-tidy
        entry: bash -c 'cd cdktf && go mod tidy'
        language: system
        pass_filenames: false
        files: ^cdktf/.*\.go$

  # CDKTF synthesis
  - repo: local
    hooks:
      - id: cdktf-synth
        name: CDKTF Synth
        entry: bash -c 'cd cdktf && cdktf synth'
        language: system
        pass_filenames: false
        files: ^cdktf/
        verbose: true

