# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for vault_agent.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
