# -------------------------------------------------------------------------------
# Oracle Watchdog Agent — Oracle Cloud Instance Recovery
#
# Project: Munchbox / Author: Alex Freidah
#
# Monitors Consul sessions from Oracle Cloud nodes and triggers OCI stop/start
# cycles when nodes become unresponsive. Runs on homelab infrastructure only.
# -------------------------------------------------------------------------------

job "oracle-watchdog" {
  region      = "global"
  datacenters = ["munchbox"]
  type        = "service"
  node_pool   = "all"
  priority    = 50

  # ---------------------------------------------------------------------------
  # Metadata
  # ---------------------------------------------------------------------------

  meta {
    managed_by = "nomad"
    project    = "munchbox"
  }

  # ---------------------------------------------------------------------------
  # Update Strategy
  # ---------------------------------------------------------------------------

  update {
    max_parallel      = 1
    health_check      = "checks"
    min_healthy_time  = "30s"
    healthy_deadline  = "3m"
    progress_deadline = "5m"
    auto_revert       = true
  }

  # ---------------------------------------------------------------------------
  # Task Group: agent
  # ---------------------------------------------------------------------------

  group "agent" {
    count = 1

    # --- Must NOT run on Oracle Cloud nodes ---
    constraint {
      attribute = "${meta.cloud}"
      operator  = "!="
      value     = "oracle"
    }

    # --- amd64 only (image built for x86_64) ---
    constraint {
      attribute = "${attr.cpu.arch}"
      value     = "amd64"
    }

    # --- Keep off GPU node ---
    constraint {
      attribute = "${node.unique.name}"
      operator  = "!="
      value     = "nomad-client-04"
    }

    network {
      mode = "host"
      port "metrics" {
        static = 9105
      }
    }

    restart {
      attempts = 3
      interval = "5m"
      delay    = "15s"
      mode     = "fail"
    }

    # --- Metrics Service (for Prometheus) ---
    service {
      name     = "oracle-watchdog-agent"
      port     = "metrics"
      provider = "consul"

      tags = [
        "traefik.enable=false",
        "prometheus",
        "metrics",
        "oracle-watchdog"
      ]

      check {
        name     = "metrics-health"
        type     = "http"
        path     = "/metrics"
        interval = "30s"
        timeout  = "5s"
      }
    }

    # -------------------------------------------------------------------------
    # Task: oracle-watchdog
    # -------------------------------------------------------------------------

    task "oracle-watchdog" {
      driver = "docker"

      # --- Vault Integration ---
      vault {
        role = "nomad-workloads"
      }

      identity {
        env  = true
        file = true
        aud  = ["vault.io"]
      }

      # --- Docker Configuration ---
      config {
        image              = "registry.munchbox.cc/oracle-watchdog:v1.4.9"
        image_pull_timeout = "5m"
        ports              = ["metrics"]

        args = [
          "-mode", "agent",
          "-config", "/etc/oracle-watchdog/config.yaml",
        ]

        volumes = [
          "local/config.yaml:/etc/oracle-watchdog/config.yaml:ro",
          "secrets/oci-config:/etc/oci/config:ro",
          "secrets/oci-key.pem:/etc/oci/key.pem:ro",
        ]
      }

      # --- OCI Private Key from Vault ---
      template {
        destination = "secrets/oci-key.pem"
        perms       = "0644"
        data        = <<-EOF
{{ with secret "secret/data/oracle-watchdog" }}{{ .Data.data.oci_private_key }}{{ end }}
        EOF
      }

      # --- OCI Config File ---
      template {
        destination = "secrets/oci-config"
        perms       = "0644"
        data        = <<-EOF
[DEFAULT]
user=ocid1.user.oc1..aaaaaaaavxaqr23tfhp2sv73yau5ha6vadqgaa7ihmbmozyuf2o26if7na2a
fingerprint=12:b2:5c:ed:6b:e8:f5:6d:6a:d5:21:c9:4c:06:3a:6f
tenancy=ocid1.tenancy.oc1..aaaaaaaaeyhaous2t76u676i73cr4wi2turtytmu2j2muyiyvrboqpsp5z7a
region=us-phoenix-1
key_file=/etc/oci/key.pem
        EOF
      }

      # --- Watchdog Configuration ---
      # The wan_dns block requires oracle-watchdog v1.4.0 or newer. Older
      # binaries silently ignore the unknown block. Bump the docker image
      # tag above before flipping wan_dns.enabled to true.
      template {
        destination = "local/config.yaml"
        perms       = "0644"
        data        = <<-EOF
# Oracle Watchdog Agent Configuration
# Generated by Nomad

# How long a node must be missing before triggering restart
timeout: 300s

# How often to check for missing sessions
check_interval: 60s

# Max restart attempts before giving up (0 = unlimited)
# Counter resets when node recovers
max_restart_attempts: 0

# Consul address for session monitoring
consul_address: "consul.service.consul:8500"

# OCI SDK configuration
oci:
  config_path: "/etc/oci/config"
  profile: "DEFAULT"

# Oracle Cloud nodes to monitor
# Names must match hostnames used by monitors (Consul KV keys)
nodes:
  - name: oraclearm1
    instance_id: "ocid1.instance.oc1.phx.anyhqljtrphwkzycwkbf7xaddhawjirqnndetdi3gbhilrocm5m4gmf52r7a"
    compartment_id: "ocid1.tenancy.oc1..aaaaaaaaeyhaous2t76u676i73cr4wi2turtytmu2j2muyiyvrboqpsp5z7a"

  - name: oraclearm2
    instance_id: "ocid1.instance.oc1.phx.anyhqljtrphwkzycnroivfk375gw4v5ibzhnvstgt4qgwipadprcrrgoya7q"
    compartment_id: "ocid1.tenancy.oc1..aaaaaaaaeyhaous2t76u676i73cr4wi2turtytmu2j2muyiyvrboqpsp5z7a"

  - name: oraclenode1
    instance_id: "ocid1.instance.oc1.phx.anyhqljtrphwkzyc25oofczrgraofa5yjgfqk2ngpaurtms4224fyjzqulpq"
    compartment_id: "ocid1.tenancy.oc1..aaaaaaaaeyhaous2t76u676i73cr4wi2turtytmu2j2muyiyvrboqpsp5z7a"

  - name: oraclenode2
    instance_id: "ocid1.instance.oc1.phx.anyhqljtrphwkzycbfjsupzwd6restfxcazav6usagueuesiglarkluylgda"
    compartment_id: "ocid1.tenancy.oc1..aaaaaaaaeyhaous2t76u676i73cr4wi2turtytmu2j2muyiyvrboqpsp5z7a"

# WAN-IP DDNS updater. Keeps the wg.munchbox.cc Cloudflare A record in
# sync with the home WAN IP so Oracle nodes can reach the WG server
# through DNS even when the residential WAN IP changes. Default-disabled;
# enable by flipping enabled to true after the v1.4.0+ image is rolled
# and the cloudflare/api_token Vault secret is verified.
wan_dns:
  enabled: true
  hostname: "wg.munchbox.cc"
  cloudflare:
    api_token_env: "CLOUDFLARE_API_TOKEN"
    zone_id: "{{ with secret "secret/data/cloudflare-wandns" }}{{ .Data.data.zone_id }}{{ end }}"
  detection_providers:
    - "https://api.ipify.org"
    - "https://1.1.1.1/cdn-cgi/trace"
  poll_interval: 5m
  cooldown: 15m

# OpenTelemetry tracing. Exports agent spans to Tempo over OTLP/HTTP; the
# endpoint is a bare host:port (4318 is HTTP; 4317 is gRPC).
tracing:
  enabled: true
  endpoint: "tempo.service.consul:4318"
        EOF
      }

      # --- Cloudflare API Token from Vault ---
      # Mounted as an env var (not a file) so the wandns package picks it
      # up via the api_token_env name in config without disk I/O. Dedicated
      # secret/cloudflare-wandns path holds a least-privilege DNS:Edit token
      # minted by terragrunt modules/cloudflare-api-token.
      template {
        destination = "secrets/cloudflare.env"
        perms       = "0600"
        env         = true
        data        = <<-EOF
{{ with secret "secret/data/cloudflare-wandns" -}}
CLOUDFLARE_API_TOKEN={{ .Data.data.api_token }}
{{- end }}
        EOF
      }

      # --- Resources ---
      resources {
        cpu    = 50
        memory = 64
      }

      # --- Termination ---
      kill_timeout = "10s"
      kill_signal  = "SIGTERM"
    }
  }
}
