# -------------------------------------------------------------------------------
# Consul ACL Configuration - Variables
#
# Project: Munchbox / Author: Alex Freidah
#
# Variable definitions for Consul ACL provisioning. Requires the bootstrap token
# generated by the initial ACL bootstrap command.
# -------------------------------------------------------------------------------

variable "consul_bootstrap_token" {
  description = "Consul ACL bootstrap token (from bootstrap command)"
  type        = string
  sensitive   = true
}
