# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for vault_cert_manager.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
