# -------------------------------------------------------------------------------
# APPROLE AUTH BACKEND FOR CHEF-MANAGED NODES
#
# Project: Munchbox / Author: Alex Freidah
#
# Chef-managed nodes auth to Vault via AppRole. Each node runs Vault Agent
# with auto-auth pointed at this backend; cinc-client's `secret('hashi_vault'
# , ...)` calls use the token Vault Agent maintains in a sink file. Per-node
# `secret_id` is generated by the operator at bootstrap and dropped at
# /etc/vault.d/secret_id; `role_id` is non-secret and dropped at
# /etc/vault.d/role_id.
#
# This is separate from `jwt-nomad`, which is for Nomad workload identity
# (per-job, JWT). Different identity model, different paths.
# -------------------------------------------------------------------------------

# --- AppRole auth backend (separate mount from the legacy ansible `approle/` mount) ---
resource "vault_auth_backend" "approle" {
  count       = var.approle_auth_enabled ? 1 : 0
  type        = "approle"
  path        = "chef-approle"
  description = "AppRole auth for chef-managed nodes (cinc-client via Vault Agent)"
}

# --- chef-managed-node role: every chef-managed node uses this same role ---
resource "vault_approle_auth_backend_role" "chef_node" {
  count          = var.approle_auth_enabled ? 1 : 0
  backend        = vault_auth_backend.approle[0].path
  role_name      = "chef-managed-node"
  token_type     = "service"
  token_ttl      = 3600
  token_max_ttl  = 86400
  token_policies = ["chef-managed-node"]
  bind_secret_id = true
}

# --- chef-managed-node policy: read access to the paths cookbooks need ---
resource "vault_policy" "chef_managed_node" {
  count = var.approle_auth_enabled && (length(var.chef_managed_node_secrets) > 0 || length(var.chef_managed_node_extra_paths) > 0) ? 1 : 0
  name  = "chef-managed-node"

  policy = <<EOT
# --- KV v2 secrets (path includes the `data/` segment because KV v2) ---
%{for secret in var.chef_managed_node_secrets~}
path "secret/data/${secret}" {
  capabilities = ["read"]
}
%{endfor~}

# --- Non-KV reads (SSH signer config/ca, etc) ---
%{for path in var.chef_managed_node_extra_paths~}
path "${path.path}" {
  capabilities = ${jsonencode(path.capabilities)}
}
%{endfor~}
EOT
}
