# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for nomad.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
