guard 'shell', name: 'Lint' do
  watch(%r{^(spec/.*_spec\.rb|recipes/.*\.rb|resources/.*\.rb|libraries/.*\.rb|attributes/.*\.rb)$}) do |m|
    puts "Linting #{m}"
    `script -q /dev/null bundle exec rake lint`
  end
end

guard 'shell', name: 'Spec' do
  watch(%r{^(spec/.*_spec\.rb|recipes/.*\.rb|resources/.*\.rb|libraries/.*\.rb|attributes/.*\.rb)$}) do |m|
    puts "Running specs for #{m}"
    `script -q /dev/null bundle exec rake spec`
  end
end
