package main

import (
	"os"
	"log"
	"strings"
	"path/filepath"

	// JSII runtime and CDKTF core
	"github.com/aws/jsii-runtime-go"
	"github.com/hashicorp/terraform-cdk-go/cdktf"

	// Nomad provider and job resource (generated by cdktf)
	"cdk.tf/go/stack/generated/hashicorp/nomad/provider"
	"cdk.tf/go/stack/generated/hashicorp/nomad/job"
)

func register_job(stack cdktf.TerraformStack, id string, hcl string) {
	job.NewJob(stack, jsii.String(id), &job.JobConfig{
		Jobspec:             jsii.String(hcl),
		DeregisterOnDestroy: true,
		PurgeOnDestroy:      true,
	})
}

func main() {
	// --- Stack Initialization ---
	app := cdktf.NewApp(nil)
	stack := cdktf.NewTerraformStack(app, jsii.String("nomad"))

	// --- Provider Configuration ---
	// TODO: Move the address to a configuration file or environment variable for flexibility.
	provider.NewNomadProvider(stack, jsii.String("nomad-provider"), &provider.NomadProviderConfig{
		Address: jsii.String("http://192.168.1.225:4646"),
	})


	// --- Job Registration ---
	// Find all Nomad job HCL files in the current directory.
	files, err := filepath.Glob("*.nomad.hcl")
	if err != nil {
		log.Fatalf("failed to glob job files: %v", err)
	}

	for _, f := range files {
		raw, err := os.ReadFile(f)
		if err != nil {
			log.Printf("failed to read file %s: %v", f, err)
			continue
		}

		hcl := strings.ReplaceAll(string(raw), "${", "$${")
		id := strings.TrimSuffix(filepath.Base(f), ".nomad.hcl")
		register_job(stack, id, hcl)
	}
	app.Synth()
}
