# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for nfs.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
