# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for cinc_client.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
