# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for vault.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
