# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    oci = {
      source  = "oracle/oci"
      version = "~> 5.0"
    }
    proxmox = {
      source  = "telmate/proxmox"
      version = "3.0.2-rc07"
    }
    consul = {
      source  = "hashicorp/consul"
      version = "~> 2.20"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 3.25"
    }
    nomad = {
      source  = "hashicorp/nomad"
      version = "~> 2.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
    bitwarden = {
      source  = "maxlaverse/bitwarden"
      version = "~> 0.12"
    }
  }
}

provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = {
      Project   = "munchbox"
      ManagedBy = "terragrunt"
    }
  }
}

provider "oci" {
  # Uses OCI config file (~/.oci/config) or environment variables
}

provider "proxmox" {
  # Uses PM_API_URL, PM_API_TOKEN_ID, PM_API_TOKEN_SECRET env vars
  pm_tls_insecure = true
}

provider "consul" {
  # Uses CONSUL_HTTP_ADDR and CONSUL_HTTP_TOKEN env vars
}

provider "vault" {
  # Uses VAULT_ADDR and VAULT_TOKEN env vars
}

provider "nomad" {
  # Uses NOMAD_ADDR and NOMAD_TOKEN env vars
}

provider "random" {
  # No configuration needed
}

provider "cloudflare" {
  # Uses CLOUDFLARE_API_TOKEN env var
}

provider "bitwarden" {
  server          = "https://vaultwarden.munchbox.cc"
  email           = "alex.freidah@gmail.com"
  master_password = "Rossignol123!@#"
}
