# playbooks/setup-nfs-mounts.yml
---
- name: Setup NFS mounts for gdrive
  hosts: all:!mccoy:!green:!logan
  become: true
  tasks:
    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Create mount points
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /mnt/gdrive
        - /mnt/gdrive-secondary

    - name: Add NFS mounts to fstab
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: nfs
        opts: defaults,_netdev
        state: mounted
      loop:
        - { path: /mnt/gdrive, src: "mccoy:/mnt/gdrive" }
        - { path: /mnt/gdrive-secondary, src: "mccoy:/mnt/gdrive-secondary" }
