# frozen_string_literal: true

# ------------------------------------------------------------------------------
#  Berksfile — Consul Cookbook Dependencies
# ------------------------------------------------------------------------------
#  Defines dependencies for the Consul cookbook.
# ------------------------------------------------------------------------------

source 'https://supermarket.chef.io'

cookbook 'nomad', path: '.'
cookbook 'firewall'
