# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for docker.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
