# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for munchbox_lib.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
