# frozen_string_literal: true

source 'https://rubygems.org'

group :test do
  gem 'rspec', '~> 3.13'
end

group :lint do
  gem 'cookstyle', '~> 8.1'
end

group :coverage do
  gem 'simplecov', '~> 0.22'
  gem 'simplecov-cobertura', '~> 2.1'
end
