# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for wireguard.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
