# -------------------------------------------------------------------------------
# Static Inventory - Bare Metal Hosts
#
# Project: Munchbox / Author: Alex Freidah
#
# Proxmox cluster nodes. Used for Ceph setup and cluster management. Assumes
# Proxmox VE is already installed from ISO on all nodes.
# -------------------------------------------------------------------------------

[proxmox_hosts]
cabot ansible_host=192.168.68.59
mccoy ansible_host=192.168.68.63
fontana ansible_host=192.168.68.65

[proxmox_cluster_master]
fontana ansible_host=192.168.68.65

[dns_servers]
green ansible_host=192.168.68.62
logan ansible_host=192.168.68.64

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
