---
all:
  children:
    nomad_servers:
      hosts:
        cabot:
          ansible_host: 192.168.68.59
        mccoy:
          ansible_host: 192.168.68.63
        stabler:
          ansible_host: 192.168.68.61
        goren:
          ansible_host: 192.168.68.60
    
    nomad_clients:
      hosts:
        cabot:
          ansible_host: 192.168.68.59
        mccoy:
          ansible_host: 192.168.68.63
        stabler:
          ansible_host: 192.168.68.61
        goren:
          ansible_host: 192.168.68.60

  vars:
    ansible_user: root
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
