# -------------------------------------------------------------------------------
# NVIDIA Role - Handlers
#
# Project: Munchbox / Author: Alex Freidah
# -------------------------------------------------------------------------------

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: reboot required
  debug:
    msg: "A reboot is required for NVIDIA drivers to take effect"
