#!/usr/bin/env python3
"""
Generate Ansible inventory from nodes.yml

Reads the single source of truth (nodes.yml) and generates:
  - ansible/inventory/hosts.yml - Host inventory with proper groups
  - Prints server IPs for verification

Usage:
  python3 scripts/generate-inventory.py
"""

import yaml
import sys
from pathlib import Path

# Paths relative to infrastructure/
SCRIPT_DIR = Path(__file__).parent
INFRA_DIR = SCRIPT_DIR.parent
NODES_FILE = INFRA_DIR / "nodes.yml"
INVENTORY_FILE = INFRA_DIR / "ansible" / "inventory" / "hosts.yml"


def load_nodes():
    """Load nodes.yml configuration."""
    with open(NODES_FILE) as f:
        return yaml.safe_load(f)


def get_all_nodes(config):
    """Combine bare_metal and vms into a single dict."""
    nodes = {}

    # Add bare-metal nodes
    for name, data in config.get("bare_metal", {}).items():
        nodes[name] = {
            "ip": data["ip"],
            "arch": data.get("arch", "amd64"),
            "roles": data.get("roles", []),
            "type": "bare_metal"
        }

    # Add VMs
    for name, data in config.get("vms", {}).items():
        nodes[name] = {
            "ip": data["ip"],
            "arch": "amd64",  # All VMs are x86_64
            "roles": data.get("roles", []),
            "type": "vm",
            "proxmox_host": data.get("proxmox_host")
        }

    return nodes


def build_inventory(config):
    """Build Ansible inventory structure."""
    nodes = get_all_nodes(config)
    proxmox = config.get("proxmox_hosts", {})

    inventory = {
        "all": {
            "children": {
                "nomad_servers": {"hosts": {}},
                "nomad_clients": {"hosts": {}},
                "consul_servers": {"hosts": {}},
                "consul_clients": {"hosts": {}},
                "vault_servers": {"hosts": {}},
                "gpu_nodes": {"hosts": {}},
                "proxmox_hosts": {"hosts": {}},
            },
            "vars": {
                "ansible_user": "root",
                "ansible_become": True,
                "ansible_python_interpreter": "/usr/bin/python3"
            }
        }
    }

    # Add Proxmox hosts
    for name, data in proxmox.items():
        inventory["all"]["children"]["proxmox_hosts"]["hosts"][name] = {
            "ansible_host": data["ip"]
        }

    # Add nodes to appropriate groups based on roles
    for name, data in nodes.items():
        host_entry = {
            "ansible_host": data["ip"],
            "static_ip": data["ip"]
        }

        roles = data.get("roles", [])

        if "nomad_server" in roles:
            inventory["all"]["children"]["nomad_servers"]["hosts"][name] = host_entry.copy()

        if "nomad_client" in roles:
            inventory["all"]["children"]["nomad_clients"]["hosts"][name] = host_entry.copy()

        if "consul_server" in roles:
            inventory["all"]["children"]["consul_servers"]["hosts"][name] = host_entry.copy()

        if "consul_client" in roles:
            inventory["all"]["children"]["consul_clients"]["hosts"][name] = host_entry.copy()

        if "vault_server" in roles:
            inventory["all"]["children"]["vault_servers"]["hosts"][name] = host_entry.copy()

        if "gpu_node" in roles:
            inventory["all"]["children"]["gpu_nodes"]["hosts"][name] = host_entry.copy()

    # Remove empty groups
    for group in list(inventory["all"]["children"].keys()):
        if not inventory["all"]["children"][group]["hosts"]:
            del inventory["all"]["children"][group]

    return inventory


def get_server_ips(config, role):
    """Get list of IPs for nodes with a specific server role."""
    nodes = get_all_nodes(config)
    return [
        data["ip"]
        for name, data in nodes.items()
        if role in data.get("roles", [])
    ]


def main():
    print("=" * 60)
    print("Generating Ansible inventory from nodes.yml")
    print("=" * 60)

    # Load config
    config = load_nodes()

    # Build and write inventory
    inventory = build_inventory(config)

    INVENTORY_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(INVENTORY_FILE, "w") as f:
        f.write("# " + "-" * 77 + "\n")
        f.write("# Ansible Inventory - AUTO-GENERATED from nodes.yml\n")
        f.write("#\n")
        f.write("# DO NOT EDIT THIS FILE DIRECTLY!\n")
        f.write("# Edit infrastructure/nodes.yml and run: make generate\n")
        f.write("# " + "-" * 77 + "\n\n")
        yaml.dump(inventory, f, default_flow_style=False, sort_keys=False)

    print(f"\nGenerated: {INVENTORY_FILE}")

    # Print summary
    print("\n" + "-" * 60)
    print("Inventory Summary:")
    print("-" * 60)

    for group, data in inventory["all"]["children"].items():
        hosts = data.get("hosts", {})
        if hosts:
            print(f"\n{group}:")
            for host, attrs in hosts.items():
                print(f"  - {host}: {attrs.get('ansible_host')}")

    # Print server IPs for cluster config
    print("\n" + "-" * 60)
    print("Server IPs (for retry_join configs):")
    print("-" * 60)

    nomad_servers = get_server_ips(config, "nomad_server")
    consul_servers = get_server_ips(config, "consul_server")
    vault_servers = get_server_ips(config, "vault_server")

    print(f"\nNomad servers: {nomad_servers}")
    print(f"Consul servers: {consul_servers}")
    print(f"Vault servers: {vault_servers}")

    print("\n" + "=" * 60)
    print("Done!")
    print("=" * 60)


if __name__ == "__main__":
    main()
