---
# -------------------------------------------------------------------------------
# Keepalived Role - Handlers
#
# Project: Munchbox / Author: Alex Freidah
#
# Service handlers for keepalived configuration changes and restarts.
# -------------------------------------------------------------------------------

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
  when: keepalived_service_enabled
