# -------------------------------------------------------------------------------
# Proxmox VM Provisioning - Variables
#
# Project: Munchbox / Author: Alex Freidah
#
# Variable definitions for VM provisioning on Proxmox using a Debian base
# template on local-lvm. Ceph and cloud-init are intentionally omitted. Root
# SSH keys baked into the template provide access for Ansible.
# -------------------------------------------------------------------------------

# -------------------------------------------------------------------------------
# Proxmox Connection
# -------------------------------------------------------------------------------

variable "proxmox_api_url" {
  description = "Proxmox API endpoint"
  type        = string
  default     = "https://192.168.68.65:8006/api2/json"
  validation {
    condition     = can(regex("^https?://[\\w\\.-]+(:\\d+)?/api2/json$", var.proxmox_api_url))
    error_message = "The Proxmox API URL must be a valid HTTP(S) URL ending with /api2/json."
  }
}

variable "proxmox_api_token_id" {
  description = "Proxmox API token ID (format: user@pve!tokenname)"
  type        = string
  sensitive   = true
  validation {
    condition     = can(regex("^[^@!]+@[^!]+![^!]+$", var.proxmox_api_token_id))
    error_message = "The Proxmox API token ID must be in the format user@pve!tokenname."
  }
}

variable "proxmox_api_token_secret" {
  description = "Proxmox API token secret"
  type        = string
  sensitive   = true
  validation {
    condition     = length(trimspace(var.proxmox_api_token_secret)) > 0
    error_message = "The Proxmox API token secret must not be empty."
  }
}

variable "proxmox_tls_insecure" {
  description = "Skip TLS verification for Proxmox API"
  type        = bool
  default     = true
}

# -------------------------------------------------------------------------------
# VM Template
# -------------------------------------------------------------------------------

variable "template_name" {
  description = "Name of the VM template to clone (Debian base on local-lvm)"
  type        = string
  default     = "debian-base"
  validation {
    condition     = length(trimspace(var.template_name)) > 0
    error_message = "The template name must not be empty."
  }
}

# -------------------------------------------------------------------------------
# Storage and Network
# -------------------------------------------------------------------------------

variable "vm_disk_storage" {
  description = "Proxmox storage ID used for VM disks"
  type        = string
  default     = "local-lvm"
  validation {
    condition     = length(trimspace(var.vm_disk_storage)) > 0
    error_message = "The VM disk storage ID must not be empty."
  }
}

variable "vm_network_bridge" {
  description = "Proxmox bridge used for VM networking"
  type        = string
  default     = "vmbr0"
  validation {
    condition     = length(trimspace(var.vm_network_bridge)) > 0
    error_message = "The VM network bridge must not be empty."
  }
}

# -------------------------------------------------------------------------------
# VM Definitions (auto-generated from nodes.yml)
# -------------------------------------------------------------------------------

variable "vms" {
  description = "Map of VMs to provision (generated by scripts/generate-tfvars.py)"
  type = map(object({
    target_node = string
    vmid        = number
    memory      = number
    cores       = number
    disk_size   = string
    gpu_passthrough = optional(object({
      pci_address = string
    }), null)
    existing = optional(bool, false)
  }))
  default = {}
  validation {
    condition = alltrue([
      for k, v in var.vms : (
        length(trimspace(v.target_node)) > 0 &&
        v.vmid > 0 &&
        v.memory > 0 &&
        v.cores > 0 &&
        can(regex("^[0-9]+[MG]$", v.disk_size))
      )
    ])
    error_message = "Each VM must have a non-empty target_node, vmid > 0, memory > 0, cores > 0, and disk_size matching the pattern (e.g., 32G, 4096M)."
  }
}
