# -------------------------------------------------------------------------------
# Proxmox VM Provisioning - Variables
#
# Project: Munchbox / Author: Alex Freidah
#
# Variable definitions for VM provisioning on Proxmox using a Debian base
# template on local-lvm. Ceph and cloud-init are intentionally omitted. Root
# SSH keys baked into the template provide access for Ansible.
# -------------------------------------------------------------------------------

# -------------------------------------------------------------------------------
# Proxmox Connection
# -------------------------------------------------------------------------------

variable "proxmox_api_url" {
  description = "Proxmox API endpoint"
  type        = string
  default     = "https://192.168.68.65:8006/api2/json"
}

variable "proxmox_api_token_id" {
  description = "Proxmox API token ID (format: user@pve!tokenname)"
  type        = string
  sensitive   = true
}

variable "proxmox_api_token_secret" {
  description = "Proxmox API token secret"
  type        = string
  sensitive   = true
}

variable "proxmox_tls_insecure" {
  description = "Skip TLS verification for Proxmox API"
  type        = bool
  default     = true
}

# -------------------------------------------------------------------------------
# VM Template
# -------------------------------------------------------------------------------

variable "template_name" {
  description = "Name of the VM template to clone (Debian base on local-lvm)"
  type        = string
  default     = "debian-base"
}

# -------------------------------------------------------------------------------
# Storage and Network
# -------------------------------------------------------------------------------

variable "vm_disk_storage" {
  description = "Proxmox storage ID used for VM disks"
  type        = string
  default     = "local-lvm"
}

variable "vm_network_bridge" {
  description = "Proxmox bridge used for VM networking"
  type        = string
  default     = "vmbr0"
}

# -------------------------------------------------------------------------------
# VM Definitions (auto-generated from nodes.yml)
# -------------------------------------------------------------------------------

variable "vms" {
  description = "Map of VMs to provision (generated by scripts/generate-tfvars.py)"
  type = map(object({
    target_node    = string
    vmid           = number
    memory         = number
    cores          = number
    disk_size      = string
    gpu_passthrough = optional(bool, false)
  }))
  default = {}
}
