version: 0.1
log:
  level: info
# OpenTelemetry tracing to Tempo
otel:
  enabled: true
  servicename: registry
  exporter:
    otlp:
      endpoint: tempo.service.consul:4318
      insecure: true
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /certs/munchbox.crt
    key: /certs/munchbox.key
  draintimeout: 10m
  readtimeout: 10m
  writetimeout: 10m
  idletimeout: 10m
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['https://registry-ui.munchbox.cc']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
    Access-Control-Allow-Credentials: ['true']
