#------------------------------------------------------------------------------
# Pre-commit configuration for chef cookbooks
#------------------------------------------------------------------------------

repos:
  - repo: local
    hooks:
      - id: cookbook-tests
        name: Cookbook Rake Lint
        entry: cookbooks/vpn/scripts/precommit.sh
        language: script
        pass_filenames: false
