# -------------------------------------------------------------------------------
# Patroni image build -- PostgreSQL 18 HA (multi-arch)
#
# Project: Munchbox / Author: Alex Freidah
# -------------------------------------------------------------------------------

IMAGE           := patroni
PG_VERSION      := 18
PATRONI_VERSION := 4.0.4
EXTRA_TAGS      := pg$(PG_VERSION) pg$(PG_VERSION)-patroni$(PATRONI_VERSION)

include ../_common.mk
