{
 "title": "HashiCorp Nomad",
 "description": "A dashboard for HashiCorp Nomad https://www.nomadproject.io/",
 "tags": [ "HashiCorp" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "query": {
     "query": "label_values(nomad_client_uptime{}, instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{instance=~\"$client\"},exported_job)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{instance=~\"$client\",exported_job=~\"$job\"},task_group)"
    }
   },
   {
    "name": "task",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\"},task)"
    }
   },
   {
    "name": "alloc_id",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\"},alloc_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_autopilot_healthy{}",
     "legendFormat": "{{ `{{` }}instance{{ `}}` }}"
    }
   ]
  },
  {
   "title": "Fault tolerance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_autopilot_failure_tolerance{}",
     "legendFormat": "fault tolerance"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\nsum(nomad_client_unallocated_cpu{})\n/\nsum(nomad_client_allocated_cpu{}\n+ nomad_client_unallocated_cpu{}) * 100",
     "legendFormat": "CPU Capacity"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\nsum(nomad_client_unallocated_memory{})\n/\nsum(nomad_client_allocated_memory{}\n+ nomad_client_unallocated_memory{}) * 100",
     "legendFormat": "Memory Capacity"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\nsum(nomad_client_unallocated_disk{})\n/\nsum(nomad_client_allocated_disk{}\n+ nomad_client_unallocated_disk{}) * 100",
     "legendFormat": "Disk Capacity"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "nomad_client_uptime{}", "legendFormat": "uptime" },
    {
     "expr": "nomad_client_allocations_running{}",
     "legendFormat": "allocations running"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_cpu{}\n/\n(nomad_client_allocated_cpu{}\n+ nomad_client_unallocated_cpu{}) * 100",
     "legendFormat": "cpu utilization"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_memory{}\n/\n(nomad_client_allocated_memory{}\n+ nomad_client_unallocated_memory{}) * 100",
     "legendFormat": "memory utilization"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_disk{}\n/\n(nomad_client_allocated_disk{}\n+ nomad_client_unallocated_disk{}) * 100",
     "legendFormat": "disk utilization"
    }
   ]
  },
  {
   "title": "Election Events",
   "type": "status-history",
   "description": "This panel should show no activity in a stable cluster. Some leadership transition events are expected, such as during cluster upgrades. Unexpected events may indicate an issue with cluster stability",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(nomad_raft_state_candidate[1m]) > 0",
     "legendFormat": "{{ `{{` }}instance{{ `}}` }} - candidate"
    },
    {
     "expr": "increase(nomad_raft_state_leader{}[1m]) > 0",
     "legendFormat": "{{ `{{` }}instance{{ `}}` }} - leader"
    }
   ]
  },
  {
   "title": "Last Contacted",
   "type": "timeseries",
   "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "nomad_raft_leader_lastContact{quantile=\"0.9\"}",
     "legendFormat": "{{ `{{` }}instance{{ `}}` }}"
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "nomad_client_allocations_blocked{instance=~\"$client\"}",
     "legendFormat": "blocked"
    },
    {
     "expr": "nomad_client_allocations_migrating{instance=~\"$client\"}",
     "legendFormat": "migrating"
    },
    {
     "expr": "nomad_client_allocations_pending{instance=~\"$client\"}",
     "legendFormat": "pending"
    },
    {
     "expr": "nomad_client_allocations_running{instance=~\"$client\"}",
     "legendFormat": "running"
    },
    {
     "expr": "nomad_client_allocations_start{instance=~\"$client\"}",
     "legendFormat": "start"
    },
    {
     "expr": "nomad_client_allocations_terminal{instance=~\"$client\"}",
     "legendFormat": "terminal"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_status_running{}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 29 },
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_complete{}",
     "legendFormat": "complete"
    },
    {
     "expr": "nomad_nomad_job_summary_failed{}",
     "legendFormat": "failed"
    },
    { "expr": "nomad_nomad_job_summary_lost{}", "legendFormat": "lost" },
    {
     "expr": "nomad_nomad_job_summary_starting{}",
     "legendFormat": "starting"
    },
    {
     "expr": "nomad_nomad_job_summary_queued{}",
     "legendFormat": "queued"
    },
    {
     "expr": "nomad_nomad_job_summary_running{}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_job_status_pending{}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nomad_nomad_job_status_dead{}", "legendFormat": "Dead" }
   ]
  },
  { "title": "Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_allocated{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"} * 1000000",
     "legendFormat": "cpu"
    },
    {
     "expr": "nomad_client_allocs_memory_allocated{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"}",
     "legendFormat": "memory"
    },
    {
     "expr": "nomad_client_allocs_memory_max_usage{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"}",
     "legendFormat": "memory max"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_percent{exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"}",
     "legendFormat": "{{ `{{` }}exported_job{{ `}}` }} - {{ `{{` }}task_group{{ `}}` }} - {{ `{{` }}task{{ `}}` }} - {{ `{{` }}instance{{ `}}` }} - {{ `{{` }}alloc_id{{ `}}` }} Mhz"
    }
   ]
  },
  {
   "title": "CPU Ticks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_ticks{exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"} * 1000000",
     "legendFormat": "{{ `{{` }}exported_job{{ `}}` }} - {{ `{{` }}task_group{{ `}}` }} - {{ `{{` }}task{{ `}}` }} - {{ `{{` }}instance{{ `}}` }} - {{ `{{` }}alloc_id{{ `}}` }} Mhz"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(nomad_client_allocs_memory_usage{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"}\n- \nnomad_client_allocs_memory_cache{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"})\n/\nnomad_client_allocs_memory_allocated{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"} * 100",
     "legendFormat": "{{ `{{` }}exported_job{{ `}}` }} - {{ `{{` }}task_group{{ `}}` }} - {{ `{{` }}task{{ `}}` }} - {{ `{{` }}instance{{ `}}` }} - {{ `{{` }}alloc_id{{ `}}` }}"
    }
   ]
  },
  {
   "title": "Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(nomad_client_allocs_memory_usage{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"}\n- \nnomad_client_allocs_memory_cache{instance=~\"$client\",exported_job=~\"$job\",task_group=~\"$group\",task=~\"$task\",alloc_id=~\"$alloc_id\"})",
     "legendFormat": "{{ `{{` }}exported_job{{ `}}` }} - {{ `{{` }}task_group{{ `}}` }} - {{ `{{` }}task{{ `}}` }} - {{ `{{` }}instance{{ `}}` }} - {{ `{{` }}alloc_id{{ `}}` }}"
    }
   ]
  },
  {
   "title": "OOM kills",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "nomad_client_allocs_oom_killed{}",
     "legendFormat": "oom"
    },
    {
     "expr": "timestamp(nomad_client_allocs_oom_killed{}) * 1000 - 3600000",
     "legendFormat": "from"
    },
    {
     "expr": "timestamp(nomad_client_allocs_oom_killed{}) * 1000 + 3600000",
     "legendFormat": "to"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(nomad_client_allocs_cpu_total_percent{}) by (exported_job,task_group,task) <= 80",
       "legendFormat": "{{ `{{` }}exported_job{{ `}}` }} - {{ `{{` }}task_group{{ `}}` }} - {{ `{{` }}task{{ `}}` }}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(\n(nomad_client_allocs_memory_usage{}\n-\nnomad_client_allocs_memory_cache{})\n/\nnomad_client_allocs_memory_allocated{} * 100\n) by (exported_job,task_group,task)",
       "legendFormat": "{{ `{{` }}exported_job{{ `}}` }} - {{ `{{` }}task_group{{ `}}` }} - {{ `{{` }}task{{ `}}` }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raft Dispatch Log",
     "type": "timeseries",
     "description": "Time to write log, mark in flight, and start replication to followers",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "nomad_raft_leader_dispatchLog{quantile=\"0.9\"}",
       "legendFormat": "Time"
      },
      {
       "expr": "increase(nomad_raft_leader_dispatchNumLogs{}[$__rate_interval])",
       "legendFormat": "Logs"
      }
     ]
    },
    {
     "title": "Raft Commit Time",
     "type": "timeseries",
     "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "nomad_raft_commitTime{quantile=\"0.9\"}",
       "legendFormat": "{{ `{{` }}instance{{ `}}` }}"
      }
     ]
    },
    {
     "title": "Raft Apply Count",
     "type": "timeseries",
     "description": "Number of Raft transactions - general indicator of the write load on the servers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(nomad_raft_apply{}[$__rate_interval])",
       "legendFormat": "{{ `{{` }}instance{{ `}}` }}"
      }
     ]
    },
    {
     "title": "Raft Append Entries",
     "type": "timeseries",
     "description": "The time it takes for a Raft transaction to be replicated to a quorum of followers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "nomad_raft_rpc_appendEntries{quantile=\"0.9\"}",
       "legendFormat": "{{ `{{` }}instance{{ `}}` }}"
      }
     ]
    },
    {
     "title": "Raft Applied Index",
     "type": "bargauge",
     "description": "Current index applied to FSM",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nomad_raft_appliedIndex{}", "legendFormat": "{{ `{{` }}instance{{ `}}` }}" }
     ]
    },
    {
     "title": "Raft FSM apply",
     "type": "timeseries",
     "description": "Time it takes for a server to apply Raft entries to the internal state machine.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "nomad_raft_fsm_apply{quantile=\"0.9\"}",
       "legendFormat": "{{ `{{` }}instance{{ `}}` }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vault",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server token TTL",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      { "expr": "nomad_nomad_vault_token_ttl{}", "legendFormat": "ttl" }
     ]
    },
    {
     "title": "Tokens",
     "type": "timeseries",
     "description": "Time elapsed to manipulate Vault tokens",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "nomad_nomad_vault_create_token{quantile=\"0.9\"}",
       "legendFormat": "create"
      },
      {
       "expr": "nomad_nomad_vault_lookup_token{quantile=\"0.9\"}",
       "legendFormat": "lookup"
      },
      {
       "expr": "nomad_nomad_vault_revoke_token{quantile=\"0.9\"}",
       "legendFormat": "revoke"
      }
     ]
    }
   ]
  }
 ]
}