{
 "title": "Pi-hole Exporter",
 "description": "A dashboard for PI-Hole Exporter from https://github.com/eko/pihole-exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Pi-hole",
    "query": "label_values(pihole_status, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "?PI-Hole", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_status{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} hostname {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pihole_domains_being_blocked{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pihole_unique_domains{hostname=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_top_queries{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} domain {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_reply{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} type {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "pihole_top_ads{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} domain {{ `}}` }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_dns_queries_all_types{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} hostname {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Ads blocked (today)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_ads_blocked_today{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} hostname {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "pihole_top_queries{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} domain {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "pihole_top_ads{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} domain {{ `}}` }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "pihole_ads_percentage_today{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} hostname {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_queries_cached{hostname=\"$hostname\"}",
     "legendFormat": "Queries cached"
    },
    {
     "expr": "pihole_queries_forwarded{hostname=\"$hostname\"}",
     "legendFormat": "Queries forwarded"
    }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_querytypes{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} type {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_forward_destinations{hostname=\"$hostname\"}",
     "legendFormat": "{{ `{{` }} destination {{ `}}` }}"
    }
   ]
  },
  {
   "title": "Unique domains",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pihole_unique_domains{hostname=\"$hostname\"}"
    }
   ]
  }
 ]
}