limit_req_zone  $binary_remote_addr  zone=resume_req_zone:10m  rate=10r/s;
limit_conn_zone $binary_remote_addr  zone=resume_conn_zone:10m;

server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  index resume.html index.html;

  limit_conn resume_conn_zone 20;

  location / {
    try_files $uri $uri/ /resume.html;
    limit_req zone=resume_req_zone burst=20 nodelay;
  }
}
