# -------------------------------------------------------------------------------
# Host Variables - goren
#
# Project: Munchbox / Author: Alex Freidah
# -------------------------------------------------------------------------------

vault_api_addr: "https://192.168.68.60:8200"
vault_cluster_addr: "https://192.168.68.60:8201"
vault_cluster_address: "192.168.68.60:8201"
