# -------------------------------------------------------------------------------
# Host Variables - nomad-client-05
#
# Project: Munchbox / Author: Alex Freidah
# -------------------------------------------------------------------------------

nomad_client_meta:
  vrrp_interface: "eth0"
