# -------------------------------------------------------------------------------
# Host Variables - oracle-node-1
#
# Project: Munchbox / Author: Alex Freidah
# -------------------------------------------------------------------------------

nomad_client_meta:
  cloud: "oracle"
  tier: "micro"
