# -------------------------------------------------------------------------------
# Cookstyle (rubocop) config for proxmox_host.
# -------------------------------------------------------------------------------

inherit_from: ../../.rubocop-base.yml
